<a href="https://colab.research.google.com/github/Sunisa78-8/phython.data.W/blob/main/02_Python101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction to Python Coding 🐍

In [37]:
print ("My first Python code!")
print ("Python is easier than I expected!!!")

My first Python code!
Python is easier than I expected!!!


To check your Python version and other extensions' version

In [38]:
!python --version

Python 3.10.12


In [39]:
!pip install --upgrade version_information
%load_ext version_information
%version_information numpy, scipy, matplotlib, sympy, version_information

The version_information extension is already loaded. To reload it, use:
  %reload_ext version_information


Software versions
Python 3.10.12 64bit [GCC 11.4.0]
IPython 7.34.0
OS Linux 5.15.109+ x86_64 with glibc2.35
numpy 1.23.5
scipy 1.10.1
matplotlib 3.7.1
sympy 1.12
version_information 1.0.4
Thu Sep 07 03:05:27 2023 UTC

To install this IPython extension

In [40]:
# you only need to do this once
!pip install --upgrade version_information

You may sometimes encounter this error. \
`ModuleNotFoundError: No module named 'pandas' in Python`

If you cannot import due to your computer cannot find, try installing the library using `pip install <library-name>`.

Begin the line with `!` to direct your code to command line

In [41]:
!pip install pandas

Help with functions

In [42]:
help(abs)

Help on built-in function abs in module builtins:

abs(x, /)
    Return the absolute value of the argument.



In [43]:
print(abs.__doc__)

Return the absolute value of the argument.


## Variables

ข้อกำหนดในการตั้งชื่อตัวแปร

* ชื่อห้ามมีเว้นวรรค
* (พยายาม)ใช้ภาษาอังกฤษ
* ตัวเล็กกับตัวใหญ่ แตกต่างกัน (case sensitive)
* ห้ามใช้ตัวเลขเป็นตัวหน้า

In [44]:
variable_a = 12
variable_b = 3.14
variable_c = "1" # ' (quote) หรือ " (double quote)
variable_d = 'Learning Pandas'
variable_e = True
variable_f = None

In [45]:
variable_ab = variable_a + variable_b
print(variable_ab)

15.14


In [46]:
print(type(variable_a))
print(type(variable_b))
print(type(variable_c))
print(type(variable_d))
print(type(variable_e))
print(type(variable_f))

<class 'int'>
<class 'float'>
<class 'str'>
<class 'str'>
<class 'bool'>
<class 'NoneType'>


Use functions: `int()`, `float()`, `str()`, `list()`, `tuple()`, `set()`, `complex()`, `ord()`, `hex()`, `oct()`, `dict()`, etc. to change type of object (type casting) in Python

In [47]:
print( float(variable_c), type(float(variable_c)) )

1.0 <class 'float'>


In [48]:
print(variable_c, type(variable_c))
new_c = int(variable_c)
print(new_c, type(new_c))

1 <class 'str'>
1 <class 'int'>


In [50]:
variable g = 1

SyntaxError: ignored

In [51]:
x = 8
X = 1e-02
x == X

False

In [52]:
y

NameError: ignored

## Operations

| Operator | Operation | Example |
|---|---|---|
| + | Addition | 5 + 2 = 7 |
| - | Subtraction | 4 - 2 = 2 |
| * | Multiplication | 2 * 3 = 6 |
| / | Division | 4 / 2 = 2 |
| // | Floor Division | 10 // 3 = 3 |
| % | Modulo | 5 % 2 = 1 |
| ** | Power | 4 ** 2 = 16 |

In [53]:
print(-1, 2+3, 7%3, 7/2, 7//2, 2**4)

-1 5 1 3.5 3 16


![order of operations](https://s3.amazonaws.com/cloudxlab/static/images/course/python-foundation-course/pemdas.png)

In [54]:
43 + 13 - 9 / 3 * 7

35.0

| Operator | Name | Example |
|---|---|---|
| = | Assignment Operator | a = 7 |
| += | Addition Assignment | a += 1 # a = a + 1 |
| -= | Subtraction Assignment | a -= 3 # a = a - 3 |
| *= | Multiplication Assignment | a *= 4 # a = a * 4 |
| /= | Division Assignment | a /= 3 # a = a / 3 |
| %= | Remainder Assignment | a %= 10 # a = a % 10 |
| **= | Exponent Assignment | a **= 10 # a = a ** 10 |

In [55]:
a = 10
b = 5

In [56]:
a += b      # a = a + b
print(a)

15


In [57]:
a *= b
print(a)

75


| Operator | Meaning | Example |
| --- | --- | --- |
| == | Is Equal To | 3 == 5 results in False |
| != | Not Equal To | 3 != 5 results in True |
| > | Greater Than | 3 > 5 results in False |
| < | Less Than | 3 < 5 results in True |
| >= | Greater Than or Equal To | 3 >= 5 results in False |
| <= | Less Than or Equal To | 3 <= 5 results in True |

In [59]:
print(3 <= 4, 3 == 4, 3 != 4, 3 > 4)

True False True False


In [60]:
True == 1

True

In [61]:
False == 0

True

In [62]:
2 == 2.000000

True

In [63]:
2 == 2.0000000000000000001

True

In [64]:
2 == 2.001

False

In [65]:
import math
help(math.isclose)

Help on built-in function isclose in module math:

isclose(a, b, *, rel_tol=1e-09, abs_tol=0.0)
    Determine whether two floating point numbers are close in value.
    
      rel_tol
        maximum difference for being considered "close", relative to the
        magnitude of the input values
      abs_tol
        maximum difference for being considered "close", regardless of the
        magnitude of the input values
    
    Return True if a is close in value to b, and False otherwise.
    
    For the values to be considered close, the difference between them
    must be smaller than at least one of the tolerances.
    
    -inf, inf and NaN behave similarly to the IEEE 754 Standard.  That
    is, NaN is not close to anything, even itself.  inf and -inf are
    only close to themselves.



In [66]:
math.isclose(2, 2.001, rel_tol=1e-03)

True

| Operator | Example | Meaning |
|---|---|---|
| and | a and b | True only if both the operands are True |
| or | a or b | True if at least one of the operands is True |
| not | not a | True if the operand is False and vice-versa |
| is | x is True | True if the operands are identical |
| is not | x is not True | True if the operands are not identical |
| in | 5 in x | True if value/variable is found in the sequence |
| not in | 5 not in x | True if value/variable is not found in the sequence |

In [67]:
print(True and True, False or True)

True True


`x = 10` (0000 1010 in binary) and `y = 4` (0000 0100 in binary)

| Operator | Meaning | Example |
| --- | --- | --- |
| & | Bitwise AND | x & y = 0 (0000 0000) |
| \| | Bitwise OR | x \| y = 14 (0000 1110) |
| ~ | Bitwise NOT | ~x = -11 (1111 0101) |
| ^ | Bitwise XOR | x ^ y = 14 (0000 1110) |
| >> | Bitwise right shift | x >> 2 = 2 (0000 0010) |
| << | Bitwise left shift | x << 2 = 40 (0010 1000) |

In [68]:
print(True & False, True | False)

False True


## Containers (Collections)  มีหลายๆค่าอยู่ในนั้น

In [69]:
a_tuple = (1, 2, 3, 4)
a_list = ['a', 'b', 'c', 'd']
a_set = {1, 2, 2, 3, 3, 3}
a_dict = {'c': 1, 'b': 2, 'a': 3}

### Tuple

In [70]:
print("The length of a_tuple:", a_tuple, "is", len(a_tuple))

The length of a_tuple: (1, 2, 3, 4) is 4


Access element in tuple or list using the name of tuple or list variable following by *square brackets* <p>
<center>`tuple_or_list_var[index]`</center>

* Index starts with zero
* Final feasible index is (length - 1)
* Negative index reverses the position from -1 to -(length)

In [72]:
print("a_tuple:", a_tuple)
print("values in each index", a_tuple[0], a_tuple[1], a_tuple[2], a_tuple[3])
print("values in each reverse index", a_tuple[-1], a_tuple[-2], a_tuple[-3], a_tuple[-4])
print("length of a_tuple", len(a_tuple))
print(a_tuple[len(a_tuple)])

a_tuple: (1, 2, 3, 4)
values in each index 1 2 3 4
values in each reverse index 4 3 2 1
length of a_tuple 4


IndexError: ignored

<font color='red'><h4>📝 Your turn</h4></font>
```
myTuple = (1,12,123,12,12,1)
```
Get the element `123` from `myTuple`


In [74]:
โจทย์  (1,12,123,1234,12345) ใหม่


SyntaxError: ignored

In [75]:
myTuple = (1,12,123,1234,12345)

In [76]:
myTuple = (1,12,123,1234,12345)
myTuple

(1, 12, 123, 1234, 12345)

In [77]:
# Get the element 123 from myTuple
myTuple[2]

123

In [78]:
# Last element ใช้ 4 -1 ก็เหมือนกัน
myTuple[4]
myTuple[-1]

12345

### List

Working with list is similar to tuple

In [80]:
print("a_list:", a_list)

a_list: ['a', 'b', 'c', 'd']


In [81]:
len(a_list)

4

In [82]:
a_list[0]

'a'

In [83]:
a_list[-1]

'd'

In [84]:
a_list.index('b')

1

In [85]:
[ i for i in range(len(a_list))  if a_list [i]]

[0, 1, 2, 3]

To display multiple elements:
* Using `list[i:j]` to display element i$^\text{th}$ to (j-1)$^\text{th}$

In [86]:
a_list[1:3]

['b', 'c']

* Iterating over a list

In [87]:
[a_list[i] for i in [0,2]]

['a', 'c']

Adding an element to a list

In [88]:
a_list.append('e')
a_list

['a', 'b', 'c', 'd', 'e']

Adding two lists concatenates them together

In [89]:
a_list + a_list

['a', 'b', 'c', 'd', 'e', 'a', 'b', 'c', 'd', 'e']

In [90]:
a_list + ['u', 'i']

['a', 'b', 'c', 'd', 'e', 'u', 'i']

Multiplying a list with an integer `n` creates a repeatation of a list `n` times

In [91]:
[1,3]*3

[1, 3, 1, 3, 1, 3]

String is a list of characters. Therefore, working with string is similar to list.

In [92]:
variable_d

'Learning Pandas'

In [93]:
print(variable_d[0])
print(variable_d[1:8])
print(variable_d[1:(variable_d.index('g')+1)])
print(variable_d[-1])
print(variable_d[1:])

L
earning
earning
s
earning Pandas


In [94]:
print(variable_d[:8])

Learning


In [95]:
variable_d[0:2]

'Le'

In [96]:
'Keep ' + variable_d

'Keep Learning Pandas'

<font color='red'><h4>📝 Your turn</h4></font>
```
variable_d = ""
```


<font color='red'><h4>📝 Your turn</h4></font>
```
variable_d = "walking a corgi in a park"
```


In [161]:
variable_f = 'walking a corgi in a park'

In [162]:
variable_f [10:15]

'corgi'

In [97]:
# get the character "P" from variable_d
variable_d[9]
Pindex = variable_d.index("P")
Pindex
variable_d[Pindex]

'P'

In [160]:
# get the word "Pandas" from variable_d
variable_d[9:]
variable_d[9:15]


'Pandas'

#### Advance list slicing
* Using [start_index:end_index:step]

In [163]:
variable_d

'Learning Pandas'

In [164]:
variable_d[::]

'Learning Pandas'

In [101]:
variable_d[::2] # display using step of 2

'Lann ads'

In [102]:
variable_d[::-1] # reversing กลับหลัง

'sadnaP gninraeL'

* `range(start_value, final_value, step)`

In [165]:
variable_d[::3]

'LrnPd'

In [170]:
list (range(0,12))  ##[::2]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [172]:
range(0,4)

range(0, 4)

In [104]:
list(range(1,5,1))

[1, 2, 3, 4]

In [173]:
list(range(0,10,2))

[0, 2, 4, 6, 8]

* `range(n)` = `range(0, n, 1)`  #เริ่ม 0-n เพิ่มทีละ 1

In [174]:
list(range(5))

[0, 1, 2, 3, 4]

`map(func, *iterables)` --> Make an iterator that computes the function using arguments from each of the iterables.  Stops when the shortest iterable is exhausted.

In [107]:
list(map(lambda x: x**2, range(5))) #ยกกำลัง 2 เลข 1-5

[0, 1, 4, 9, 16]

### Set

In [175]:
print("a_set = {1, 2, 2, 3, 3, 3}")
print("a_set:", a_set)

a_set = {1, 2, 2, 3, 3, 3}
a_set: {1, 2, 3}


In [176]:
len(a_set)

3

Casting set ot list

In [177]:
list(a_set)

[1, 2, 3]

In [111]:
list(a_set)[0]

1

### Dict

Python dictionary stores data in key-value format

In [112]:
print("a_dict = {'c': 1, 'b': 2, 'a': 3}")
print("a_dict:", a_dict)

a_dict = {'c': 1, 'b': 2, 'a': 3}
a_dict: {'c': 1, 'b': 2, 'a': 3}


In [113]:
a_dict.keys()

dict_keys(['c', 'b', 'a'])

In [114]:
a_dict.values()

dict_values([1, 2, 3])

In [115]:
len(a_dict)

3

In [116]:
a_dict.items()

dict_items([('c', 1), ('b', 2), ('a', 3)])

In [117]:
for key,val in a_dict.items():
    print("key of", key, "gives value of", val)

key of c gives value of 1
key of b gives value of 2
key of a gives value of 3


In [118]:
a_dict['c']

1

In [119]:
a_dict['a']

3

In [120]:
# add key "d" with value "4" to a_dict
a_dict["d"] = 4
a_dict

{'c': 1, 'b': 2, 'a': 3, 'd': 4}

<font color='red'><h4>📝 Your turn</h4></font>
<p>Create a dictionary from the following lists

```
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
```

In [121]:
# create my_dict
my_dict = {'Ten': 10, 'Twenty': 20, 'Thirty': 30}
my_dict['Twenty']

20

In [122]:
keys = ['Ten', 'Twenty', 'Thirty']
values = [10, 20, 30]
print("zip(keys,values):", zip(keys, values))
print("convert zip(keys,values) to list:", list(zip(keys, values)))
my_dict1 = dict(zip(keys, values))
my_dict1

zip(keys,values): <zip object at 0x7888cb5eab00>
convert zip(keys,values) to list: [('Ten', 10), ('Twenty', 20), ('Thirty', 30)]


{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

In [123]:
my_dict2 = {}
for i in range(len(keys)):
  my_dict2[keys[i]] = values[i]
my_dict2

{'Ten': 10, 'Twenty': 20, 'Thirty': 30}

## Vectors and Arrays

In [124]:
import numpy as np # package สำหรับทำงานกับข้อมูลที่เป็นตัวเลข (ในรูปแบบ matrix)

Create numpy array

In [125]:
np_a = np.array([[1,2,3],[4,5,6]])
np_a

array([[1, 2, 3],
       [4, 5, 6]])

The size of a matrix can be accessed using `matrix.shape` resulting in (#rows,#columns)

In [126]:
np_a.shape # ดูว่ากี่แถวกี่หลัก

(2, 3)

In [127]:
np_a.shape[0] #จำนวนแถวเท่าไหร่

2

In [128]:
n_rows,n_cols = np_a.shape
print(n_rows, n_cols)

2 3


In [129]:
np_b = np.array([[1,4],[2,5],[3,6]])
print(np_b.shape)
np_b

(3, 2)


array([[1, 4],
       [2, 5],
       [3, 6]])

In [130]:
np.zeros((3,2)) # สร้าง 0

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [181]:
np.random.randn(3,2)  # ให้สุ่มเลข

array([[ 0.1761739 , -0.86938515],
       [ 0.05722331,  1.59444747],
       [ 0.12381618,  1.53939703]])

In [182]:
np.random.randint(0, 10, (3,2)) # random integers from 0 to 9 ฟิคค่า น้อยและมาก

array([[0, 2],
       [0, 1],
       [4, 9]])

Indexing: [row,column] where using `:` as index means to select all elements in rows or columns

In [133]:
print(np_b)
np_b[0,1]  # =ชี้

[[1 4]
 [2 5]
 [3 6]]


4

<font color='red'><h4>📝 Your turn</h4></font>

Retrieve the element `3` from `np_b`

In [134]:
# Retrieve the element 3 from np_b
np_b[2,0]


3

In [135]:
np_b[1]

array([2, 5])

In [136]:
np_b[1, :] #แถวที่ 1 ทุกหลัก

array([2, 5])

In [137]:
np_b[1:3, 1:]

array([[5],
       [6]])

Transpose matrix

In [138]:
np_b.T

array([[1, 2, 3],
       [4, 5, 6]])

matrix multiplication

In [139]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [140]:
np_b

array([[1, 4],
       [2, 5],
       [3, 6]])

In [141]:
np.dot(np_b,np_a)

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [184]:
np.dot(np_a,np_b) #*กัน

array([[14, 32],
       [32, 77]])

In [185]:
np_a * np_b

ValueError: ignored

In [144]:
np_a

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
np_a * np_a

In [147]:
np_a + 1

array([[2, 3, 4],
       [5, 6, 7]])

In [146]:
np_a * 3

array([[ 3,  6,  9],
       [12, 15, 18]])

Useful numpy functions

In [148]:
print(np_a)
np.sum(np_a)

[[1 2 3]
 [4 5 6]]


21

In [149]:
np.sum(np_a, axis=0)  #axis ไว้เจาะจง 0 คือ ยุบแถว บวกตามแถว

array([5, 7, 9])

In [186]:
np.sum(np_a, axis=1) # บวกของหลัก

array([ 6, 15])

In [151]:
np.mean(np_a)

3.5

In [152]:
np.mean(np_a, axis=0) # compute mean along the row axes

array([2.5, 3.5, 4.5])

In [153]:
np.mean(np_a, axis=1) # compute mean along the column axes

array([2., 5.])

In [154]:
np_a.max(axis=0)

array([4, 5, 6])

## Pandas Series
One-dimensional ndarray with axis labels \
https://pandas.pydata.org/docs/reference/api/pandas.Series.html#pandas.Series

In [155]:
import pandas as pd

In [156]:
calories = {"day1": 420, "day2": 380, "day3": 390}
diet = pd.Series(calories)
#myseries = pd.Series([420, 380, 390], index=["day1","day2","day3"])
diet

day1    420
day2    380
day3    390
dtype: int64

In [157]:
diet["day2"]

380

In [188]:
diet[0]

420

In [159]:
diet.mean()

396.6666666666667

## Pandas Dataframe
Two-dimensional tabular data \
https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.html#pandas.DataFrame

### Creating a dataframe

![createDF](https://pbpython.com/images/pandas-dataframe-shadow.png)

In [189]:
import pandas as pd

In [190]:
d = {'No': [1, 2, 3, 4, 5],
     'Name': ["สมบูรณ์", "สมชาย", "สมหญิง", "สมหมาย", "สมบัติ"],
     'Age': [23, 45, 62, 30, 32]}
df = pd.DataFrame(data = d)
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [ ]:
type(df)

In [204]:
df.columns
#list(df.columns)

Index(['No', 'Name', 'Age'], dtype='object')

In [205]:
df.index
#list(df.index)

RangeIndex(start=0, stop=5, step=1)

In [206]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   No      5 non-null      int64 
 1   Name    5 non-null      object
 2   Age     5 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 248.0+ bytes


In [207]:
df.head()
#df.tail()

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [208]:
df.describe()

No        Age
count  5.000000   5.000000
mean   3.000000  38.400000
std    1.581139  15.404545
min    1.000000  23.000000
25%    2.000000  30.000000
50%    3.000000  32.000000
75%    4.000000  45.000000
max    5.000000  62.000000

In [209]:
df.describe(include='all')

No     Name        Age
count   5.000000        5   5.000000
unique       NaN        5        NaN
top          NaN  สมบูรณ์        NaN
freq         NaN        1        NaN
mean    3.000000      NaN  38.400000
std     1.581139      NaN  15.404545
min     1.000000      NaN  23.000000
25%     2.000000      NaN  30.000000
50%     3.000000      NaN  32.000000
75%     4.000000      NaN  45.000000
max     5.000000      NaN  62.000000

### Selecting data

In [210]:
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [211]:
df["Name"]

0    สมบูรณ์
1      สมชาย
2     สมหญิง
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

In [212]:
df[["Name"]]

Name
0  สมบูรณ์
1    สมชาย
2   สมหญิง
3   สมหมาย
4   สมบัติ

In [213]:
df[["Name", "Age"]]

Name  Age
0  สมบูรณ์   23
1    สมชาย   45
2   สมหญิง   62
3   สมหมาย   30
4   สมบัติ   32

In [214]:
df["Name"]
#type(df["Name"]) # pandas.core.series.Series

0    สมบูรณ์
1      สมชาย
2     สมหญิง
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

![ilocvsloc](https://sparkbyexamples.com/wp-content/uploads/2021/10/pandas-difference-loc-vs-iloc.png)

In [191]:
df

No     Name  Age
0   1  สมบูรณ์   23
1   2    สมชาย   45
2   3   สมหญิง   62
3   4   สมหมาย   30
4   5   สมบัติ   32

In [202]:
df.loc[df[ "Age"]>40]


No    Name  Age
1   2   สมชาย   45
2   3  สมหญิง   62

In [192]:
df.iloc[1,2]

45

In [193]:
df["Name"]=="สมหมาย"

0    False
1    False
2    False
3     True
4    False
Name: Name, dtype: bool

In [194]:
df.loc[df["Name"]=="สมหมาย",:]
#df.loc[df["Name"]=="สมหมาย"]

No    Name  Age
3   4  สมหมาย   30

<font color='red'><h4>📝 Your turn</h4></font>

In [195]:
# Retrieve "สมหญิง" from df
df.iloc[2,1]
df.loc[df["Name"]=="สมหญิง","Name"]
df.loc[df["Name"]=="สมหญิง"]["Name"]

2    สมหญิง
Name: Name, dtype: object

In [196]:
# Get "Name" of people in df whose "Age" are less than 40 year's old
df.loc[df["Age"]<40,"Name"]




0    สมบูรณ์
3     สมหมาย
4     สมบัติ
Name: Name, dtype: object

## Controlling program flow

### Condition: if-elif-else

In [197]:
'a' if 3 < 4 else 'b'

'a'

In [199]:
'a' if 4 < 3 else 'b'

'b'

```python
if เงื่อนที่เราจะตรวจสอบ (โดยอาศัยสัญลักษณ์เหล่านี้ ==, !=, <, >, <=, >=, in, is_null()) :
    ถ้าเงื่อนไขเป็นจริง ทำ
```

In [198]:
if 1 < 5:
    print('yes')

yes


```python
if เงื่อนไขที่จะตรวจสอบ (โดยใช้สัญลักษณ์ ==,!=,<,>,<=,>=):
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ 1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ 2
elif เงื่อนไขที่จะตรวจสอบต่อไปถ้าเงื่อนไขข้างบนไม่เป็นจริง:
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ a1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ a2
elif เงื่อนไขที่จะตรวจสอบต่อไปถ้าเงื่อนไขข้างบนไม่เป็นจริง:
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ b1
    ถ้าเงื่อนไขเป็นจริง ทำงานที่ b2
else: #ตรวจสอบเงื่อนไขข้างบนแล้วไม่เป็นจริง
    ทำงานที่ X
```
Note: จะไม่ `elif` หรือไม่มีก็ได้

In [215]:
import numpy as np

# random a real number between 60 to 100
score = np.random.uniform(60, 100)
print("score =", np.round(score,2))

if score > 90:
    print('A')
elif score > 80:
    print('B')
else:
    print('C')

score = 94.93
A


### Loop: for
```python
for ตัวแปรที่เราจะรับค่าจากลิสต์ in ลิสต์ที่ต้องการจะวนลูป:
    do something
    do another thing
this is outside the loop
```
Note: indent using 4 spaces

In [ ]:
food = ['chiken', 'shabu', 'vegetable']

In [216]:
for i in food:
    print("I like to eat", i)

NameError: ignored

In [ ]:
for i in range(10, 20, 2):
    print(i, i**2)

In [ ]:
xs = []
for x in range(5):
    if x % 2 == 0:
        xs.append(x)
xs

Using `for` loop to create a list

In [ ]:
[x**2 for x in range(5)]

In [ ]:
[x**2 for x in range(5) if x % 2 == 0]

In [ ]:
[x**2 if x % 2 == 0 else -1 for x in range(5)]

### Loop: for, while
```python
while true_condition:
    do something
```
Note: indent using 4 spaces

In [ ]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    count += 1

In [ ]:
max_count = 5
count = 0
while (count < max_count):
    print(count)
    # break while loop if count = 3
    if count == 3:
        break
    count += 1

### Function
```python
def ชื่อฟังก์ชั่น(input1,input2,....):
    do something
    do another thing
    return output
```

In [217]:
# Hello
# """
# Hello, my name is Meow!
# Hi!
# """

In [218]:
def f(x):
    """Say something about the function here."""
    return x

In [219]:
f("Hello Pythonions!")

'Hello Pythonions!'

In [221]:
f(3.14)

3.14

In [220]:
def compute_sum(a, b):
    """Calculate the sum of a and b."""
    return a + b

In [222]:
compute_sum(3,4)

7

In [223]:
def h(a= 0 , b = 1, c = 2):
    """Cacluates some complicated mathematical function."""
    return a + 2*b + 3*c

In [224]:
h()

8

In [225]:
h(1,1,2)

9

In [229]:
h(a=1)

9

In [226]:
h(c=3,b=2,a=1)

14

In [227]:
def func1(s):
    """
    Print a string 's' and tell how many characters it has
    s: a given string
    """
    print(s + " has " + str(len(s)) + " characters")

In [ ]:
func1("Hello!")

In [230]:
help(func1)

Help on function func1 in module __main__:

func1(s)
    Print a string 's' and tell how many characters it has
    s: a given string



## Using libraries

### math library

In [ ]:
import math
math.pi

In [ ]:
print(dir(math))

In [ ]:
help(math)

In [ ]:
help(math.log)

In [ ]:
math.log(math.e)

In [ ]:
math.log(4)

In [ ]:
math.log(4, 2)

### numpy library

In [ ]:
np.linspace(0, 1, 11)

In [ ]:
from numpy.random import rand
rand(4)

- Some other very useful modules form the Python standard library are `os`, `sys`, `shutil`, `re`, etc.
- A complete lists of standard modules for Python 3 is available at http://docs.python.org/3/library/